#!/usr/bin/env bash

[[ "$(whoami)" = "root" ]] && echo "Script must be run as a normal user." && exit

# Colors
RED="\033[1;31m"
GREEN="\033[1;32m"
END="\033[0m"

update() {
  echo -e "\n${GREEN}Downloading the latest version...${END}"
  curl https://llaun.ch/jar -o /tmp/jar
  unzip /tmp/jar -d /tmp/llaunch
  sudo mv /tmp/llaunch/*.jar /usr/share/llaunch/llaunch.jar
  rm /tmp/jar
  rm -rf /tmp/llaunch/
  echo -e "\n${GREEN}Done!${END}"
}

usage() {
  echo "
  Usage:
    --update, update | Update llaunch.jar
    --remove, remove | Remove llaunch from your system, except your \$HOME/.minecraft dir 
    nothing          | Launch TLauncher
  "
}

remove() {
  SYSTEM_FILES=(
    /usr/share/llaunch
    /usr/share/icons/llaunch.png
    /usr/share/applications/llaunch.desktop
    /usr/bin/llaunch
  )
  echo -e "\n${GREEN}Removing Legachy Launcher system files...${END}"
  rm -rf "${SYSTEM_FILES[@]}"
  echo -en "\nDo you want to keep all those java packages installed (${GREEN}Yy${END}/${RED}Nn${END})?" && read -r KEEP_JAVA
  echo -en "\nDo you want to keep your \$HOME/.tlauncher dir (${GREEN}Yy${END}/${RED}Nn${END})?" && read -r KEEP_DOTDIR
  [[ "${KEEP_JAVA,,}" = "n" ]] && sudo pacman -Rns zulu-21-bin
  [[ "${KEEP_DOTDIR,,}" = "n" ]] && rm -rf "$HOME/.tlauncher"
}


case "$1" in
  -u|--update|update)
    update ; exit ;;
  -r|--remove|remove)
    remove ; exit ;;
  *)
    usage  ; exit ;;
esac


java -jar /usr/share/llaunch/llaunch.jar
